### ISSUE TITLE
part 3 feedback

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/JuliaFrederick-project#2]
My various comments, listed in no particular order:

I was not able to run these files:
All of your R scripts  - problem with file paths. Use the ‘here’ package.

Please remove any folders/files and text inside files that are not part of your project.

Provide instructions on what the different files/folders contain and what to do to reproduce everything.

To present univariate results of categorical variables, you can use either tables or some of the dot-plots we’ve done in previous exercises. While I generally prefer figures, for some of the data you have a few tables might work best.

For your bi-variate tables (though applies to figures too), consider what the most important findings are and show them in nicely formatted figures such that the main results are easy to grasp. And further explorations or additional minor results can go into supplementary materials.

The main document should be like a research paper, with a bit more in-depth initial data exploration, but without showing much details that are only important during cleaning/wrangling. Those can go into supplementary materials or the separate R/Rmd scripts inside the appropriate folders. I suggest to not show any R code in your manuscript, that could show up in the supplement or in the supplementary files. Think of the main document like a regular peer-reviewed manuscript, e.g. like Brian’s project you saw at the beginning of the semester.

Your methods section should contain information explaining the different statistical/modeling approaches you take (e.g. for your tree, you should explain how it was created somewhere as part of the methods).

If you want more feedback on specific aspects, let me know either by replying to this Issue or email.

**Comment by JuliaFrederick** [comment]
I believe I have fixed the problem running the project. Theoretically you should just have to run the project_template.Rmd file that produces the word document, and it'll pull from all of the other r scripts I have. It works for me, hopefully it works for you. I am currently working on updating figures/tables, and doing a more in depth write up. 
**I would really appreciate if you would check that it is now reproducible on your end.** 
Thank you!

**Comment by andreashandel** [comment]
i just tried again and all R scripts ran this time.
